# -*- coding: utf-8 -8-
"""Settings

Attributes:
    TWITTER_CONSUMER_KEY
    TWITTER_CONSUMER_SECRET
    TWITTER_ACCESS_TOKEN
    TWITTER_ACCESS_TOKEN_SECRET

"""
# Twitter
TWITTER_CONSUMER_KEY = '1edbJ0RswuNVVfmhiXDz3tMtY'
TWITTER_CONSUMER_SECRET = 'MQleCAeXtNkCHU0P5LHFETPpySxK46bh4A25CxNT76aG6Uq2Hc'
TWITTER_ACCESS_TOKEN = '17479200-o7Q1EEIXnsQnKlaPJuMlUbBThfLyUVp0sINi6668y'
TWITTER_ACCESS_TOKEN_SECRET = 'zkrsRSJNRJwobouNTDRyre0dTrLvFJ4isWOyTepq0T2Rc'

# Mongo
MONGO_HOST = 'localhost'
MONGO_PORT = '27017'
MONGO_DB = ''
MONGO_USER = ''
MONGO_PASSWORD = ''
